### PR TITLE
Removed 2 Rules

### PR DESCRIPTION
**Pull request by tjdharamsi**
Rules for dd-mm-yyyy and mm-dd-yyyy have been removed which were unstable after "-" bug-fix.

### CODE REVIEW

**Comment by michaelMinar** [comment]
why were they unstable?

**Review by michaelMinar — APPROVED** [review]
Why are they unstable after the bug fix? can you be a little more descriptive before merging?

**Comment by tjdharamsi** [comment]
Based on the current structure of the RULES, anything with -yyyy would be translated to UTCOffset as a result they two rules become redundant. Earlier they use to give error because of the "+" typo.

**Comment by michaelMinar** [comment]
So it's superfluous? or will we not be able to parse some valid date formats?

**Comment by tjdharamsi** [comment]
With the current structure of RULES they were superfluous.

**Pull request merged**
